apiVersion: batch/v1
kind: Job
metadata:
  name: presync-label-storage-node
  namespace: openshift-local-storage
spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              for i in `oc get nodes -o name`; do
                oc label $i cluster.ocs.openshift.io/openshift-storage=''
                echo "Worker node $i is labeled with cluster.ocs.openshift.io/openshift-storage=''"
              done
          imagePullPolicy: IfNotPresent
          name: presync-label-storage-node
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
