---
kind: Secret
apiVersion: v1
metadata:
  name: bmc-super1-blazer-cars-lab
  namespace: blazer-cars-lab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
    avp_path: "secret/data/vplugin/bmc"
type: Opaque
stringData:
  username: <username>
  password: <password> 
---
kind: Secret
apiVersion: v1
metadata:
  name: bmc-super2-blazer-cars-lab
  namespace: blazer-cars-lab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
    avp_path: "secret/data/vplugin/bmc"
type: Opaque
stringData:
  username: <username>
  password: <password> 
---
kind: Secret
apiVersion: v1
metadata:
  name: bmc-super3-blazer-cars-lab
  namespace: blazer-cars-lab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
    avp_path: "secret/data/vplugin/bmc"
type: Opaque
stringData:
  username: <username>
  password: <password> 
