---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super1
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  config:
    dns-resolver:
      config:
        server:
        - 10.40.0.100
        - fd00:6:6:11::52
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super2
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  config:
    dns-resolver:
      config:
        server:
        - 10.40.0.100
        - fd00:6:6:11::52
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-super3
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "6"
spec:
  config:
    dns-resolver:
      config:
        server:
        - 10.40.0.100
        - fd00:6:6:11::52
